version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
  oracle-database-xe-18400-slim:
    container_name: oracle-database-xe-18400-slim
    image: gvenzl/oracle-xe:18.4.0-slim
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=password
      - ORACLE_DATABASE=ORCLPDB1
    volumes:
      - ./src/main/resources/db/startup:/container-entrypoint-startdb.d
      - oradata-xe-18400-slim:/opt/oracle/oradata
volumes:
  oradata-xe-18400-slim: