alter session set container=ORCLPDB1;

ALTER USER streaming DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON users;

GRANT
    CONNECT,
    CREATE SESSION,
    ALTER SESSION,
    RESOURCE
TO streaming;

GRANT
    CREATE TABLE,
    CREATE VIEW,
    CREATE ANY TRIGGER,
    CREATE ANY PROCEDURE,
    CREATE SEQUENCE,
    CREATE SYNONYM
TO streaming;